#!/bin/sh
xrandr --output DVI-D-0 --off --output HDMI-0 --off --output DVI-I-1 --mode 1920x1200 --pos 3840x536 --rotate normal --output DVI-I-0 --off --output DP-1 --primary --mode 3840x2160 --pos 0x0 --rotate normal --output DP-0 --off
