#!/bin/sh
xrandr --output DVI-D-0 --off --output HDMI-0 --off --output DVI-I-1 --mode 1920x1200 --pos 1920x0 --rotate normal --output DVI-I-0 --off --output DP-1 --primary --mode 1920x1080 --pos 0x60 --rotate normal --output DP-0 --off
